global:
  checkNewVersion: true
  sendAnonymousUsage: false
log:
  level: INFO
accessLog: {}
api:
  dashboard: true
  insecure: true

entryPoints:
  code-dev-hmr:
    address: ":81"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
